"""
Success Criteria Analysis
-------------------------
    This file was generated by Claude Sonnet 4.6. We prompted it with:
        Create a success criteria  file that analyzes the motion quality and musical alignment of our dancing robot
        to the timed beats. Be sure to include visual plots.
"""

import numpy as np
 
 
class SuccessTracker:
    def __init__(self, n_joints=14, settling_threshold_rad=0.175):
        self.n_joints = n_joints
        self.settling_threshold = settling_threshold_rad
 
        # musical alignment
        self.timing_errors_ms = []
 
        # motion quality
        self.settling_times_ms = []
        self._settling_start = None
        self._current_target = None
        self._settled = False
 
    def log_cue(self, target_time, actual_time, target_action=None):
        """Call when a new cue fires."""
        self.timing_errors_ms.append((actual_time - target_time) * 1000)
 
        if target_action is not None:
            action_arr = np.array(target_action).flatten()
            self._current_target = action_arr[:self.n_joints]
            self._settling_start = actual_time
            self._settled = False
 
    def log_step(self, obs, current_action, current_time=None):
        """Call every env step."""
        if self._current_target is None or self._settled:
            return
 
        positions = np.array(obs["robot0_joint_pos"])
        error = np.max(np.abs(positions - self._current_target))
 
        if error < self.settling_threshold:
            if current_time is not None and self._settling_start is not None:
                self.settling_times_ms.append((current_time - self._settling_start) * 1000)
            self._settled = True
 
    def report(self, save_path="success_criteria.png"):
        """Print success criteria and save plots to file."""
 
        import matplotlib
        matplotlib.use("agg")
        import matplotlib.pyplot as plt
        import matplotlib.gridspec as gridspec
        from matplotlib.lines import Line2D
 
        has_timing   = bool(self.timing_errors_ms)
        has_settling = bool(self.settling_times_ms)
 
        # ── Console output ─────────────────────────────────────────────
        print("\n========== SUCCESS CRITERIA ==========")
 
        print("\n[ Musical Alignment ]")
        if has_timing:
            errors   = self.timing_errors_ms
            mean_err = np.mean(errors)
            std_err  = np.std(errors)
            pct_50   = sum(abs(e) <= 50  for e in errors) / len(errors) * 100
            pct_100  = sum(abs(e) <= 100 for e in errors) / len(errors) * 100
            print(f"  Total cues:         {len(errors)}")
            print(f"  Mean timing error:  {mean_err:+.1f} ms  {'(running late)' if mean_err > 0 else '(running early)'}")
            print(f"  Std dev:            {std_err:.1f} ms")
            print(f"  Within +-50ms:      {pct_50:.1f}%  {'pass' if pct_50 >= 80 else 'FAIL'}  (target: 80%)")
            print(f"  Within +-100ms:     {pct_100:.1f}%")
        else:
            print("  No cue data recorded.")
 
        print("\n[ Motion Quality ]")
        if has_settling:
            mean_settle = np.mean(self.settling_times_ms)
            pct_fast    = sum(s <= 200 for s in self.settling_times_ms) / len(self.settling_times_ms) * 100
            print(f"  Mean settling time: {mean_settle:.0f} ms  {'pass' if mean_settle < 200 else 'FAIL'}  (target: <200ms)")
            print(f"  Poses that settled: {len(self.settling_times_ms)}")
            print(f"  Settled <200ms:     {pct_fast:.1f}%  {'pass' if pct_fast >= 70 else 'FAIL'}  (target: 70%)")
        else:
            print("  No settling data (pass target_action to log_cue and current_time to log_step).")
 
        print("\n======================================\n")
 
        if not has_timing and not has_settling:
            print("No data to plot.")
            return
 
        # ── Colours ────────────────────────────────────────────────────
        BLUE  = "#4C72B0"
        GREEN = "#55A868"
        RED   = "#C44E52"
 
        fig = plt.figure(figsize=(14, 8))
        fig.suptitle("Dancing Robot - Success Criteria", fontsize=15, fontweight="bold")
        gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.45, wspace=0.35)
 
        # ── 1. Timing error histogram ──────────────────────────────────
        ax1 = fig.add_subplot(gs[0, 0])
        if has_timing:
            errors = self.timing_errors_ms
            ax1.hist(errors, bins=20, color=BLUE, edgecolor="white", alpha=0.85)
            ax1.axvline(0,   color="black", linewidth=1.2, linestyle="--", label="perfect")
            ax1.axvline(-50, color=RED,     linewidth=1,   linestyle=":",  label="+-50ms")
            ax1.axvline( 50, color=RED,     linewidth=1,   linestyle=":")
            ax1.set_xlabel("Timing Error (ms)")
            ax1.set_ylabel("Count")
            ax1.set_title("Timing Error Distribution")
            ax1.legend(fontsize=8)
            ax1.text(0.97, 0.95,
                     f"mean={np.mean(errors):+.1f}ms\nstd={np.std(errors):.1f}ms",
                     transform=ax1.transAxes, ha="right", va="top", fontsize=8,
                     bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.8))
        else:
            ax1.text(0.5, 0.5, "No timing data", ha="center", va="center",
                     transform=ax1.transAxes, color="grey")
            ax1.set_title("Timing Error Distribution")
 
        # ── 2. Timing error per cue (scatter) ─────────────────────────
        ax2 = fig.add_subplot(gs[0, 1])
        if has_timing:
            errors = self.timing_errors_ms
            idx    = list(range(len(errors)))
            colors = [GREEN if abs(e) <= 50 else RED for e in errors]
            ax2.scatter(idx, errors, c=colors, s=30, alpha=0.85, zorder=3)
            ax2.axhline( 0,  color="black", linewidth=0.8, linestyle="--")
            ax2.axhline( 50, color=RED,     linewidth=0.8, linestyle=":")
            ax2.axhline(-50, color=RED,     linewidth=0.8, linestyle=":")
            ax2.set_xlabel("Cue #")
            ax2.set_ylabel("Timing Error (ms)")
            ax2.set_title("Timing Error per Cue")
            ax2.legend(handles=[
                Line2D([0],[0], marker="o", color="w", markerfacecolor=GREEN, markersize=7, label="within +-50ms"),
                Line2D([0],[0], marker="o", color="w", markerfacecolor=RED,   markersize=7, label="outside +-50ms"),
            ], fontsize=8)
        else:
            ax2.text(0.5, 0.5, "No timing data", ha="center", va="center",
                     transform=ax2.transAxes, color="grey")
            ax2.set_title("Timing Error per Cue")
 
        # ── 3. Settling time histogram ─────────────────────────────────
        ax3 = fig.add_subplot(gs[1, 0])
        if has_settling:
            stimes = self.settling_times_ms
            ax3.hist(stimes, bins=15, color=GREEN, edgecolor="white", alpha=0.85)
            mean_s = np.mean(stimes)
            ax3.axvline(mean_s, color=RED,   linewidth=1.5, linestyle="--", label=f"mean={mean_s:.0f}ms")
            ax3.axvline(200,    color="grey", linewidth=1,   linestyle=":",  label="200ms target")
            ax3.set_xlabel("Settling Time (ms)")
            ax3.set_ylabel("Count")
            ax3.set_title("Pose Settling Times")
            ax3.legend(fontsize=8)
        else:
            ax3.text(0.5, 0.5, "No settling data", ha="center", va="center",
                     transform=ax3.transAxes, color="grey")
            ax3.set_title("Pose Settling Times")
 
        # ── 4. Summary bar chart ───────────────────────────────────────
        ax4 = fig.add_subplot(gs[1, 1])
        labels, values, targets, bar_colors = [], [], [], []
 
        if has_timing:
            errors  = self.timing_errors_ms
            pct_50  = sum(abs(e) <= 50  for e in errors) / len(errors) * 100
            pct_100 = sum(abs(e) <= 100 for e in errors) / len(errors) * 100
            labels     += ["Within +-50ms", "Within +-100ms"]
            values     += [pct_50, pct_100]
            targets    += [80, 90]
            bar_colors += [GREEN if pct_50 >= 80 else RED, GREEN if pct_100 >= 90 else RED]
 
        if has_settling:
            pct_fast = sum(s <= 200 for s in self.settling_times_ms) / len(self.settling_times_ms) * 100
            labels     += ["Settled <200ms"]
            values     += [pct_fast]
            targets    += [70]
            bar_colors += [GREEN if pct_fast >= 70 else RED]
 
        bars = ax4.bar(labels, values, color=bar_colors, edgecolor="white", alpha=0.85)
        for bar, val, tgt in zip(bars, values, targets):
            ax4.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 1,
                     f"{val:.0f}%", ha="center", va="bottom", fontsize=10, fontweight="bold")
            ax4.axhline(tgt, color="grey", linewidth=0.8, linestyle="--")
        ax4.set_ylim(0, 110)
        ax4.set_ylabel("% of Cues")
        ax4.set_title("Success Criteria Summary")
        ax4.tick_params(axis="x", labelsize=9)
 
        plt.savefig(save_path, dpi=150, bbox_inches="tight", facecolor="white")
        plt.close()
        print(f"Plot saved to {save_path}")
 